import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/authProvider";
import { ThemeProvider } from "@/context/themeProvider";
import { Navbar } from "@/components/Nav";
import "./globals.css";
import { SideNav, SideNavMobile } from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <AuthProvider>
            <Navbar />
            <SideNav />
            <SideNavMobile>
              <SideNav isMobileView={true} />
            </SideNavMobile>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
